version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress-container-consultorio
    ports:
      - "8083:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress_db
    depends_on:
      - db
    volumes:
      - wordpress_data:/var/www/html

  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mariadb-container-consultorio
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wordpress_data:
  db_data:
